In [1]:
import numpy as np

In [2]:
A=np.array([1,2,3,4,5,6,7,8])

In [3]:
print(A)

[1 2 3 4 5 6 7 8]


In [4]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [5]:
print(a)
type(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [6]:
t=np.transpose(a)
print(t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
zm=np.zeros((3,2))

In [9]:
zm

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
#ones
one=np.ones((3,2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
#Append
np.append(zm,one)

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [12]:
#insert
ins=np.insert(A,3,10)

In [13]:
ins

array([ 1,  2,  3, 10,  4,  5,  6,  7,  8])

In [14]:
dele=np.delete(A,3)
dele

array([1, 2, 3, 5, 6, 7, 8])

In [15]:
#concatenate
np.concatenate((a,a),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

### Stack

In [16]:
np.hstack((a,a))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [17]:
np.vstack((a,a))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#split
np.vsplit(a,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [19]:
a[1,2]

6

In [20]:
A[::4]

array([1, 5])

In [21]:
#empty matrix it create a address for an empty matrix
np.empty((3,3))

array([[4.67296746e-307, 1.69121096e-306, 3.22647253e-307],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.29061142e-306, 5.53353523e-322]])

In [22]:
#random=it creates matrix with random numbers
rand=np.random.random((3,3))
rand

array([[1.24548079e-02, 6.42979734e-01, 8.41010537e-01],
       [8.24536175e-04, 3.15655671e-01, 2.05714834e-01],
       [3.58118750e-01, 2.36694269e-01, 3.66799621e-01]])